### ISSUE TITLE
3 Talk about the financial services... what can it really offer?

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/investment-insights-for-asset-managers#13]
**Blog Title:** The power of financial services... what can it really offer?

**About:** Talk about the power of the financial services, what and why each service being used.
Don't talk about how just talk about why and what.

**Comment by data-henrik** [comment]
Audience? Would this FinTech developers or solution architects?
I understand the value of each individual service. But will I understand why I should use them? What makes this unique or stand out?

(I am happy to help writing it.)

**Comment by Twanawebtech** [comment]
This issue coved here: https://www.ibm.com/blogs/bluemix/2017/08/developing-finance-application-using-ibm-cloud/
