### ISSUE TITLE
1 Give intro to FinTrade

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/investment-insights-for-asset-managers#15]
Give intro to FinTrade, how it's been developed, what services we used, technologies. Describe the business case same to what we did in the script.

**Comment by Twanawebtech** [comment]
Title: Introducing FinTrade, the financial trading application using IBM Cloud

Drafted blog post: https://admin.blogs.prd.ibm.event.ibm.com/blogs/bluemix/?p=103455&preview=1&_ppp=266fa2a52b

Open for reviews...

**Comment by VidyasagarMSC** [comment]
@Twanawebtech Planning to publish this blog to DZone for more reach. What say??

**Comment by Twanawebtech** [comment]
Yes, that would be good. Go for it...

**Comment by VidyasagarMSC** [comment]
Published on Medium - https://medium.com/@VidyasagarMSC/when-ai-guides-your-investment-7ed0cad0592

Dzone rejected the post stating it as a promotional post :(
