### ISSUE TITLE
Use IBM AppID service instead of auth0

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/investment-insights-for-asset-managers#25]
It seems like both have similar functionality. Let's use the IBM service to:

- test it out
- give feedback to the dev team
- compare features & UX to auth0

**Comment by VidyasagarMSC** [comment]
I can help with this as I worked on this for one of the Interconnect labs.

**Comment by BeeryHolstein** [comment]
For usage of App ID the secure OpenWhisk See https://console.bluemix.net/docs/apis/management/manage_apis.html#manage_apis and specifically see the “Editing API settings” section.
