### ISSUE TITLE
Show "Watson's view" (with annotations) when clicking on an article

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/investment-insights-for-asset-managers#36]
Currently, when clicking on an article, it opens in a new tab. 

To illustrate how Watson Discovery annotates and "sees" an article, it would be great to show an "annotated" view similar to what the tone analyzer demo provides: https://tone-analyzer-demo.mybluemix.net/

![screenshot_2834](https://user-images.githubusercontent.com/7142658/28672099-0e568468-72df-11e7-9e33-66d4c3f192bd.jpg)

... not trivial, but something to think about longer term

**Comment by Twanawebtech** [comment]
Adding this to milestone 4.  Would be nice to have that added for the final demo.

**Comment by l2fprod** [comment]
@uwefassnacht @Twanawebtech 

It does not seem that Watson Discovery provides any metadata on the body like Tone Analyzer does to come up with such a display.

**Comment by Twanawebtech** [comment]
@l2fprod yes that's correct, discovery news is not providing any metadata for the body. 
See full API output here: https://fintrade.mybluemix.net/api/news

We could pass the body to Tone service and do it that way.
