### ISSUE TITLE
Display discovery API output some

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/investment-insights-for-asset-managers#64]
Display discovery API output somewhere like below.

https://discovery-news-demo.mybluemix.net/
<img width="497" alt="screenshot 2017-08-03 10 12 56" src="https://user-images.githubusercontent.com/12715466/28914684-8a825fc6-7834-11e7-84be-d8b10e6e386f.png">

**Comment by Twanawebtech** [comment]
moving this to backlog if you want to pick that up @VidyasagarMSC if not then I do it.

**Comment by VidyasagarMSC** [comment]
@Twanawebtech Yep, Will take it up.

**Comment by VidyasagarMSC** [comment]
Coded and pushed to master.
