### ISSUE TITLE
Blog post 08 - Predictive Marketing Scenarios and Simulated analytics services

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix/investment-insights-for-asset-managers#77]
- How to create & consume Predictive Marketing Scenarios service and Simulated Analytics service?
- How are these two services related?
- How is Stressed price calculateD?

**Comment by Twanawebtech** [comment]
Content covered here: https://www.ibm.com/blogs/bluemix/2017/09/investment-insights-asset-managers-depth/
