### ISSUE TITLE
Prediction file not taken the correct shock value, always positive 

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/investment-insights-for-asset-managers#89]
The prediction file not taken the correct shock value, shockvalue is taken instead of resultsCounterOut which has positive or negative. 

Line number 255 on home.controller.js

**Comment by Twanawebtech** [comment]
Looking at the example below, 1.3 is sent as a whole number, this is 1.3 negative value but it translates to the service as a positive value I suspect. 

As of now, I am not sure how "Predictive market scenario" distinguish between positive or negative numbers. In the screenshot below, it should be 1.3 negative so how should we do the calculation to take the negative value.  

@robert-hodgson1 can you help with answering that? how do we distinguish between positive and negative numbers for the **Predictive market scenario** service?

<img width="601" alt="screenshot 2017-08-24 12 31 55" src="https://user-images.githubusercontent.com/12715466/29654090-5d18b864-88c9-11e7-9da1-1d2683a7dee2.png">

**Comment by robert-hodgson1** [comment]
Hi Twana,

The shock value passed to the scenario should be calculated as:

(shock value passed to service) =  1+ (shock value change in % )/100


So if you have a shock value of -5% this corresponds to 0.95 when passed to the service. 5% would be 1.05.

So a shock of 1 to the service represents no change, <1 is a negative chang, >1 is a positive change.

Let me know if you have any questions.

Rob

**Comment by Twanawebtech** [comment]
Ok let me verify for these two examples: 

**Example 1**
Shock value negative 1.3% = 0.987


**Example 2**
Shock value postive 1.3% = 1.113

Is that correct?

**Comment by VidyasagarMSC** [comment]
So,There's no change in the predictive market scenarios code.

**Comment by robert-hodgson1** [comment]
example 1 is correct, example 2 should be 1.013.
